
CC=g++
CFLAGS=-std=c++11 -Wall -g

q3: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

q2: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

q1: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

FindLatticePoints: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

FindNumSqNums: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

FindAllCombinations: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

FORCE:

