
CC=g++
CFLAGS=-std=c++11 -Wall -g

FindNumSetsCollinearPts: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

FindNumPairs4AutomorphicShift: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

FindNumOfBitOne: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm
FindNumOfOne: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

CentralSphere: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm
BinomialCoefficient: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm
Roots2Coeffs: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm



FORCE:
