
CC=g++
CFLAGS=-std=c++11 -Wall -g

FindNumOfBitOne: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm
FindNumOfOne: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm

CentralSphere: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm
BinomialCoefficient: % : %.cpp FORCE
	$(CC) $(CFLAGS) $< -o $@ -lm



FORCE:
